/// <reference lib="webworker" />
import type { BrainManifest, FlappyState, Mode } from '../types'; import { FlyEncoder } from './FlyEncoder'; import { FlyDecoder } from './FlyDecoder'; import { DEFAULT_READOUT, inferReadout, type ReadoutModel } from './Readout'; import { onlineLearningThreshold, trainedFlapRequest } from './TrainedFlightPolicy';
declare const self: DedicatedWorkerGlobalScope;
interface Meta{n:number;types:string[];superclasses:string[];params:{dt:number;tau:number;gain:number;tonic:number;noise_hz:number;noise_amp:number};typeIdx:Uint16Array;classIdx:Uint8Array;side:Uint8Array}
let meta:Meta,colPtr:Uint32Array,rowIdx:Uint32Array,code:Uint8Array,lut:Float32Array,v:Float32Array,drive:Float32Array,current:Float32Array,fired:Int32Array,activity:Uint8Array;let firedCount=0,totalSpikes=0,rng=1,model:ReadoutModel={...DEFAULT_READOUT,weights:[...DEFAULT_READOUT.weights]},traces=new Float32Array(model.features.length),trainingSamples=0,trainingLoss=.693;const decoder=new FlyDecoder(),trainedDecoder=new FlyDecoder(2,260),groups=new Map<string,Int32Array>(),teacherDelay:number[]=[];
const post=(message:unknown,transfer?:Transferable[])=>self.postMessage(message,transfer??[]);
self.onmessage=async e=>{try{const m=e.data;if(m.type==='INIT')await init(m.manifest,m.shared,m.savedModel);else if(m.type==='STEP')step(m.state,m.mode,m.elapsed);else if(m.type==='RESET')reset(m.seed);else if(m.type==='FAST_TRAIN')void fastTrain(m.iterations);else if(m.type==='IMPORT_MODEL')importModel(m.model)}catch(error){post({type:'ERROR',message:error instanceof Error?error.message:String(error)})}};
async function init(info:BrainManifest,shared:boolean,saved?:ReadoutModel){post({type:'PROGRESS',value:.13,label:'Loading neuron metadata…'});meta=parseMeta(await fetchGz(['/brain/meta.bin']));const base=await (await fetch('/brain/readout.json')).json() as ReadoutModel;model={...base,weights:[...base.weights]};if(saved?.features?.join('|')===model.features.join('|')&&saved.weights?.length===model.weights.length){model={...saved,weights:[...saved.weights]};trainingSamples=Math.max(0,saved.trainingSamples??0);trainingLoss=saved.trainingLoss??trainingLoss}traces=new Float32Array(model.features.length);const weights=parseWeights(await fetchGz(info.parts.map(p=>`/brain/${p}`),info.weights_mb,x=>post({type:'PROGRESS',value:.18+x*.7,label:`Loading compressed connectome… ${Math.round(x*100)}%`})));({colPtr,rowIdx,code,lut}=weights);if(meta.n!==info.neurons||weights.n!==info.neurons||weights.nnz!==info.connections)throw new Error('fly.ai export integrity check failed');v=new Float32Array(meta.n);drive=new Float32Array(meta.n);current=new Float32Array(meta.n);fired=new Int32Array(meta.n);const useShared=shared&&typeof SharedArrayBuffer!=='undefined',ab=useShared?new SharedArrayBuffer(meta.n):new ArrayBuffer(meta.n);activity=new Uint8Array(ab);for(const side of ['L','R'] as const)for(const name of ['LC4','LPLC2','LC10a'])groups.set(`${name}_${side}`,cells(name,side));for(const name of model.features)groups.set(name,featureCells(name));groups.set('DNp01',cells('DNp01'));post({type:'PROGRESS',value:.97,label:'Initializing descending neurons…'});if(useShared)post({type:'READY',activityBuffer:ab});else post({type:'READY'})}
async function fetchGz(urls:string[],totalMb=0,progress?:(x:number)=>void){const chunks:Uint8Array[]=[];let got=0;for(const url of urls){const cache=await caches.open('fly-connectome-v1');let res=await cache.match(url);if(!res){res=await fetch(url);if(res.ok)await cache.put(url,res.clone())}if(!res.ok||!res.body)throw new Error(`${url}: HTTP ${res.status}`);const reader=res.body.getReader();for(;;){const {done,value}=await reader.read();if(done)break;chunks.push(value);got+=value.length;progress?.(Math.min(.98,got/Math.max(1,totalMb*1e6)))}}const blob=new Blob(chunks as BlobPart[]);if(chunks[0]?.[0]!==0x1f||chunks[0]?.[1]!==0x8b)return blob.arrayBuffer();return new Response(blob.stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()}
function magic(view:DataView,want:string){const got=String.fromCharCode(view.getUint8(0),view.getUint8(1),view.getUint8(2),view.getUint8(3));if(got!==want)throw new Error(`Expected ${want}, got ${got}`)}
function parseMeta(buf:ArrayBuffer):Meta{const view=new DataView(buf);magic(view,'FLYM');const n=view.getUint32(8,true),len=view.getUint32(12,true),head=JSON.parse(new TextDecoder().decode(new Uint8Array(buf,16,len)));let at=16+len;const typeIdx=new Uint16Array(buf.slice(at,at+2*n));at+=2*n;const classIdx=new Uint8Array(buf,at,n);at+=n;return{n,types:head.types,superclasses:head.superclasses,params:head.params,typeIdx,classIdx,side:new Uint8Array(buf,at,n)}}
function parseWeights(buf:ArrayBuffer){const view=new DataView(buf);magic(view,'FLYW');const n=view.getUint32(8,true),nnz=view.getUint32(12,true),lnMin=view.getFloat32(16,true),bytes=new Uint8Array(buf);let at=20;const varint=()=>{let x=0,shift=0,b=0;do{b=bytes[at++];x+=(b&127)*2**shift;shift+=7}while(b&128);return x};const colPtr=new Uint32Array(n+1);for(let j=0;j<n;j++)colPtr[j+1]=colPtr[j]+varint();const rowIdx=new Uint32Array(nnz);for(let j=0;j<n;j++){let row=0;for(let e=colPtr[j],first=true;e<colPtr[j+1];e++,first=false){row=first?varint():row+varint();rowIdx[e]=row}}const code=bytes.slice(at,at+nnz),lut=new Float32Array(256);for(let q=0;q<128;q++){const mag=Math.exp(lnMin*(1-q/127));lut[q]=mag;lut[q|128]=-mag}return{n,nnz,colPtr,rowIdx,code,lut}}
function cells(name:string,side?:'L'|'R'){const th=meta.types.map(t=>t===name),ch=meta.superclasses.map(t=>t===name),s=side==='L'?1:side==='R'?2:0,out:number[]=[];for(let i=0;i<meta.n;i++)if((th[meta.typeIdx[i]]||ch[meta.classIdx[i]])&&(!s||meta.side[i]===s))out.push(i);return Int32Array.from(out)}
function featureCells(feature:string){const match=feature.match(/^(.*) ([LR])$/);if(!match)return cells(feature);const side=match[2] as 'L'|'R',sets:Record<string,string[]>={TARGET_DN:['DNae002','DNae001','DNg111','DNge109','DNb01','DNg13','DNge103','DNp54'],LOOM_DN:['DNa07','DNae004','DNg40','DNp04','DNp06','DNp103','DNp34','DNp35','DNp71','DNpe025','DNpe045','DNpe056'],ESCAPE_DN:['DNp01','DNp04','DNg40','DNp71']},names=sets[match[1]];if(!names)return cells(match[1],side);const all:number[]=[];for(const name of names)all.push(...cells(name,side));return Int32Array.from(new Set(all))}
function stimulate(ids:Int32Array|undefined,amount:number){if(ids)for(let k=0;k<ids.length;k++)drive[ids[k]]+=amount}
function neuralStep(){current.fill(0);for(let k=0;k<firedCount;k++){const j=fired[k];for(let e=colPtr[j];e<colPtr[j+1];e++)current[rowIdx[e]]+=lut[code[e]]}const p=meta.params,decay=Math.exp(-p.dt/p.tau),pNoise=p.noise_hz*p.dt;let count=0;activity.fill(0);for(let i=0;i<meta.n;i++){let x=decay*v[i]+p.gain*current[i]+p.tonic+drive[i];if(random()<pNoise)x+=p.noise_amp;if(x>=1){fired[count++]=i;activity[i]=255;x=0}else activity[i]=Math.min(180,Math.max(0,x*85));v[i]=x;drive[i]=0}firedCount=count;totalSpikes+=count}
function rate(name:string){const ids=groups.get(name)??new Int32Array();let hits=0;for(const id of ids)if(activity[id]===255)hits++;return Math.min(1,hits/Math.max(1,ids.length*.3))}
function step(state:FlappyState,mode:Mode,elapsed:number){const start=performance.now(),s=FlyEncoder.encode(state);stimulate(groups.get('LC4_L'),s.lc4);stimulate(groups.get('LC4_R'),s.lc4);stimulate(groups.get('LPLC2_L'),s.lplc2);stimulate(groups.get('LPLC2_R'),s.lplc2);stimulate(groups.get('LC10a_L'),s.lc10Left+s.upward*.35);stimulate(groups.get('LC10a_R'),s.lc10Right+s.downward*.35);neuralStep();const dnp01=rate('DNp01'),raw=model.features.map(rate);for(let i=0;i<traces.length;i++)traces[i]=traces[i]*.86+raw[i]*.14;const learned=inferReadout(traces,model),threshold=onlineLearningThreshold(trainingSamples,model.threshold),flapRequested=trainedFlapRequest(state,learned,threshold),probability=learned;
  if(mode==='trained')onlineTrain(state);const decision=mode==='pure'?decoder.decide(elapsed*1000,dnp01>0):trainedDecoder.decide(elapsed*1000,flapRequested);const frame=new Uint8Array(8192);for(let i=0;i<frame.length;i++)frame[i]=activity[Math.floor(i*activity.length/frame.length)];const readoutModel=mode==='trained'&&trainingSamples%25===0?{...model,weights:[...model.weights],mean:model.mean&&[...model.mean],scale:model.scale&&[...model.scale],trainingSamples,trainingLoss}:undefined;post({type:'BRAIN_RESULT',result:{timestamp:performance.now(),decision,flapProbability:mode==='trained'?probability:undefined,activity:{...s,dnp01},totalSpikes,stepTime:performance.now()-start,activityFrame:frame.buffer,activityFrameLength:frame.length,trainingSamples,trainingLoss,readoutModel}},[frame.buffer])}
function teacher(state:FlappyState){const below=state.birdY>state.gapCenterY+8;const falling=state.birdVelocityY>-60;const danger=state.birdY>state.gapBottom-38;return below&&falling||danger?1:0}
function onlineTrain(state:FlappyState){const y=teacher(state),p=inferReadout(traces,model),weight=y?2:1,gradient=(p-y)*weight,lr=.018;for(let i=0;i<model.weights.length;i++){const x=(traces[i]-(model.mean?.[i]??0))/(model.scale?.[i]??1);model.weights[i]=Math.max(-6,Math.min(6,model.weights[i]-lr*(gradient*x+.0005*model.weights[i])))}model.bias=Math.max(-4,Math.min(4,model.bias-lr*gradient));const loss=-(y*Math.log(Math.max(1e-6,p))+(1-y)*Math.log(Math.max(1e-6,1-p)));trainingLoss=trainingSamples?trainingLoss*.98+loss*.02:loss;trainingSamples++}
async function fastTrain(iterations:number){const total=Math.max(400,Math.min(5000,Math.floor(iterations||1200))),xs:Float32Array[]=[],ys:number[]=[],labels:number[]=[];reset(rng);let birdY=320,velocity=0,gapCenter=320,pipeX=480;for(let i=0;i<total;i++){if(i%150===0){v.fill(0);drive.fill(0);current.fill(0);traces.fill(0);labels.length=0;firedCount=0;gapCenter=155+random()*310;birdY=120+random()*400;velocity=-140+random()*300;pipeX=350+random()*180}velocity+=22.4;birdY+=velocity*.02;const state:FlappyState={birdY,birdVelocityY:velocity,pipeX,pipeWidth:72,gapTop:gapCenter-105,gapBottom:gapCenter+105,gapCenterY:gapCenter,distanceToPipe:pipeX-112};const label=teacher(state);labels.push(label);if(label)velocity=-355;pipeX-=2.64;const s=FlyEncoder.encode(state);stimulate(groups.get('LC4_L'),s.lc4);stimulate(groups.get('LC4_R'),s.lc4);stimulate(groups.get('LPLC2_L'),s.lplc2);stimulate(groups.get('LPLC2_R'),s.lplc2);stimulate(groups.get('LC10a_L'),s.lc10Left+s.upward*.35);stimulate(groups.get('LC10a_R'),s.lc10Right+s.downward*.35);neuralStep();const raw=model.features.map(rate);for(let k=0;k<traces.length;k++)traces[k]=traces[k]*.86+raw[k]*.14;if(labels.length>5){xs.push(new Float32Array(traces));ys.push(labels.shift()!)}if(i%50===0){post({type:'TRAINING_PROGRESS',done:Math.round((i+1)*.7),total,loss:trainingLoss});await new Promise(r=>setTimeout(r,0))}}
  const trainIdx=xs.map((_,i)=>i).filter(i=>i%5!==0),validIdx=xs.map((_,i)=>i).filter(i=>i%5===0),d=model.features.length,mean=Array(d).fill(0),scale=Array(d).fill(0);for(const i of trainIdx)for(let k=0;k<d;k++)mean[k]+=xs[i][k]/trainIdx.length;for(const i of trainIdx)for(let k=0;k<d;k++)scale[k]+=(xs[i][k]-mean[k])**2/trainIdx.length;for(let k=0;k<d;k++)scale[k]=Math.max(.025,Math.sqrt(scale[k]));const positives=trainIdx.reduce((a,i)=>a+ys[i],0),negatives=trainIdx.length-positives;model={...model,weights:Array(d).fill(0),bias:Math.log((positives+1)/(negatives+1)),mean,scale};const posWeight=negatives/Math.max(1,positives);let bestLoss=Infinity,bestWeights=[...model.weights],bestBias=model.bias;for(let epoch=0;epoch<120;epoch++){const gw=Array(d).fill(0);let gb=0;for(const i of trainIdx){const p=inferReadout(xs[i],model),g=(p-ys[i])*(ys[i]?posWeight:1);gb+=g;for(let k=0;k<d;k++)gw[k]+=g*(xs[i][k]-mean[k])/scale[k]}const lr=.12;for(let k=0;k<d;k++)model.weights[k]-=lr*(gw[k]/trainIdx.length+.001*model.weights[k]);model.bias-=lr*gb/trainIdx.length;const loss=validationLoss(validIdx,xs,ys);if(loss<bestLoss){bestLoss=loss;bestWeights=[...model.weights];bestBias=model.bias}if(epoch%12===0){post({type:'TRAINING_PROGRESS',done:Math.round(total*(.72+epoch/430)),total,loss});await new Promise(r=>setTimeout(r,0))}}model.weights=bestWeights;model.bias=bestBias;
  model.weights[0]=Math.max(.8,model.weights[0]);model.weights[1]=Math.min(-.8,model.weights[1]);for(const k of [4,5,10,11])model.weights[k]=Math.max(.35,model.weights[k]);let best=.42,bestScore=-1;for(let t=.2;t<=.7;t+=.01){let tp=0,tn=0,p=0,n=0;for(const i of validIdx){const y=ys[i],hit=inferReadout(xs[i],model)>=t;if(y){p++;if(hit)tp++}else{n++;if(!hit)tn++}}const score=tp/Math.max(1,p)+tn/Math.max(1,n);if(score>bestScore){bestScore=score;best=t}}model.threshold=Math.min(.5,best);trainingLoss=validationLoss(validIdx,xs,ys);trainingSamples+=xs.length;reset(rng);post({type:'TRAINING_PROGRESS',done:total,total,loss:trainingLoss});post({type:'TRAINING_DONE',model:{...model,weights:[...model.weights],mean:[...mean],scale:[...scale],trainingSamples,trainingLoss},samples:trainingSamples,loss:trainingLoss})}
function validationLoss(idx:number[],xs:Float32Array[],ys:number[]){let loss=0;for(const i of idx){const p=inferReadout(xs[i],model);loss-=Math.log(Math.max(1e-6,ys[i]?p:1-p))}return loss/Math.max(1,idx.length)}
function importModel(next:ReadoutModel){if(!next||next.features?.join('|')!==model.features.join('|')||next.weights?.length!==model.weights.length||!next.weights.every(Number.isFinite)||!Number.isFinite(next.bias)||!Number.isFinite(next.threshold))throw new Error('Imported readout model is incompatible or invalid');model={...next,weights:[...next.weights]};trainingSamples=Math.max(1000,next.trainingSamples??0);trainingLoss=next.trainingLoss??trainingLoss;traces.fill(0);post({type:'TRAINING_DONE',model:{...model,weights:[...model.weights],trainingSamples,trainingLoss},samples:trainingSamples,loss:trainingLoss})}
function reset(seed:number){v?.fill(0);drive?.fill(0);current?.fill(0);activity?.fill(0);traces.fill(0);teacherDelay.length=0;firedCount=0;totalSpikes=0;rng=seed>>>0;decoder.reset();trainedDecoder.reset()}
function random(){rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296} export{};
