import './styles/global.css'; import { FlappyGame } from './game/FlappyGame'; import { GameRenderer } from './renderer/GameRenderer'; import { BrainRenderer } from './renderer/BrainRenderer'; import { FlyBrain } from './brain/FlyBrain'; import { FlyEncoder } from './brain/FlyEncoder'; import { loadManifest } from './brain/BrainLoader'; import { ExperimentHistory } from './experiment/ExperimentHistory'; import type { AppState, BrainActivity, BrainResult, Mode } from './types';
const empty:BrainActivity={lc4:0,lplc2:0,lc10Left:0,lc10Right:0,upward:0,downward:0,dnp01:0};
export class App {
  private state:AppState='BOOT'; private mode:Mode='pure'; private slow=false; private autoRevive=false; private flyId=ExperimentHistory.nextFlyId(); private seed=Number(new URLSearchParams(location.search).get('seed'))||Date.now();
  private game!:FlappyGame; private brain!:FlyBrain; private gameRenderer!:GameRenderer; private brainRenderer!:BrainRenderer;private activity=empty;private result?:BrainResult;private last=performance.now();private brainClock=0;private renderClock=0;private fps=60;private frames=0;private fpsAt=performance.now();private latency=0;private autoTimer=0;
  constructor(private root:HTMLElement){this.paint();this.bind();void this.boot()}
  private paint(){this.root.innerHTML=`<main><header><div><div class="eyebrow">BIOLOGICAL COMPUTATION / EXPERIMENT 01</div><h1><span>🪰</span> A FLY BRAIN <em>PLAYS FLAPPY BIRD</em></h1><p>A real fruit fly connectome attempts the impossible.</p></div><div class="facts"><b>166,700 <small>NEURONS</small></b><b>~25.6M <small>CONNECTIONS</small></b><b class="frozen">● FROZEN <small>CONNECTOME</small></b></div></header>
<section class="workspace"><article class="panel brain"><div class="panel-title"><span>01 / FLY BRAIN</span><i>LIVE ACTIVITY</i></div><canvas id="brain"></canvas><div class="brain-meta"><strong>166,700</strong><span>NEURON ACTIVITY MAP<br>WEBGL / ${crossOriginIsolated?'SHARED MEMORY':'TRANSFER BUFFER'}</span></div><div id="sequence" class="sequence">WAITING FOR SENSORY INPUT</div></article>
<article class="panel game"><div class="panel-title"><span>02 / FLIGHT ARENA</span><i id="flyLabel">FLY #${this.flyId}</i></div><div class="canvas-wrap"><canvas id="game"></canvas><div id="death" class="death hidden"></div></div></article>
<article class="panel data"><div class="panel-title"><span>03 / NEURAL DATA</span><i>50 HZ</i></div><h2>VISUAL INPUT</h2><div id="sensors"></div><h2>MOTOR OUTPUT</h2><div id="motor"></div><div class="decision"><small>DECISION</small><strong id="decision">· WAIT</strong><span id="prob"></span></div><h2>BEST FLIES <small>THIS BROWSER</small></h2><ol id="leaders"></ol></article></section>
<section class="status"><div><small>SCORE</small><b id="score">0</b></div><div><small>BEST</small><b id="best">${ExperimentHistory.best()}</b></div><div><small>GAME</small><b id="fps">60 FPS</b></div><div><small>BRAIN</small><b>50 HZ</b></div><div><small>STEP</small><b id="step">— MS</b></div><div><small>MODE</small><b id="modeLabel">PURE</b></div></section>
<nav><div class="mode"><button id="pure" class="active">PURE BRAIN</button><button id="trained">TRAINED READOUT</button></div><button id="fastTrain">⚡ FAST TRAIN</button><button id="exportModel">EXPORT MODEL</button><button id="importModel">IMPORT MODEL</button><input id="modelFile" class="hidden" type="file" accept="application/json,.json"><button id="slow">SLOW BRAIN</button><label><input id="auto" type="checkbox"> AUTO REVIVE</label><button id="restart">RESTART</button></nav>
<footer><strong>SCIENTIFIC NOTE</strong><p>The connectome is derived from the MaleCNS v1.0 fruit-fly neural connectivity dataset. Flappy Bird sensory encoding and motor decoding are artificial experimental interfaces. The connectome remains frozen.</p></footer></main><div id="training" class="training hidden"><div><div class="eyebrow">FROZEN CONNECTOME / READOUT ONLY</div><h2>FAST TRAINING</h2><p id="trainText">Generating teacher demonstrations…</p><div class="track"><i id="trainBar"></i></div><b id="trainPct">0%</b></div></div><div id="toast" class="toast hidden"></div><div id="loading" class="loading"><div class="loader-card"><div class="fly-icon">🪰</div><div class="eyebrow">INITIALIZING BIOLOGICAL NETWORK</div><h2>LOADING A<br>FRUIT FLY BRAIN...</h2><div class="load-stat"><span id="loadText">Locating connectome…</span><b id="loadPct">0%</b></div><div class="track"><i id="loadBar"></i></div><div class="online"><span>166,700 NEURONS</span><span>25,088,107 ACTIVE CONNECTIONS</span></div><button id="wake" class="hidden">WAKE UP FLY →</button><div id="loadError" class="load-error"></div></div></div>`}
  private bind(){this.gameRenderer=new GameRenderer(this.$('game'));this.brainRenderer=new BrainRenderer(this.$('brain'));this.game=new FlappyGame(this.seed,(cause)=>this.die(cause));this.$b('pure').onclick=()=>this.setMode('pure');this.$b('trained').onclick=()=>this.setMode('trained');this.$b('fastTrain').onclick=()=>this.fastTrain();this.$b('exportModel').onclick=()=>this.exportModel();this.$b('importModel').onclick=()=>this.$<HTMLInputElement>('modelFile').click();this.$<HTMLInputElement>('modelFile').onchange=e=>void this.importModel((e.target as HTMLInputElement).files?.[0]);this.$b('slow').onclick=()=>{this.slow=!this.slow;this.$b('slow').classList.toggle('active',this.slow)};this.$b('restart').onclick=()=>this.restart();this.$<HTMLInputElement>('auto').onchange=e=>this.autoRevive=(e.target as HTMLInputElement).checked;this.$b('wake').onclick=()=>this.start()}
  private async boot(){this.state='LOADING_CONNECTOME';try{const manifest=await loadManifest(p=>this.progress(p.value,p.label));this.brain=new FlyBrain();this.brain.onProgress=(v,l)=>this.progress(v,l);this.brain.onResult=r=>this.onBrain(r);this.brain.onTrainingProgress=(done,total,loss)=>this.trainingProgress(done,total,loss);this.brain.onTrainingDone=(model,samples,loss)=>this.trainingDone(model,samples,loss);let saved:unknown;try{saved=JSON.parse(localStorage.getItem('fly-readout-v2')??'null')}catch{saved=undefined}await this.brain.init(manifest,saved);this.progress(1,'BRAIN ONLINE');this.state='READY';this.$b('wake').classList.remove('hidden')}catch(error){this.state='ERROR';this.$('loadError').innerHTML=`<b>CONNECTOME NOT AVAILABLE</b><p>${error instanceof Error?error.message:String(error)}</p><p>Place the verified fly.ai web export in <code>public/brain/</code>, then reload. No simulated fallback was used.</p>`}}
  private start(){if(this.state==='ERROR')return;this.state='RUNNING';this.$('loading').classList.add('hidden');this.game.start();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
  private loop(now:number){if(this.state!=='RUNNING')return;const scale=this.slow?.1:1,dt=Math.min(.033,(now-this.last)/1000)*scale;this.last=now;this.game.update(dt);this.brainClock+=dt;while(this.brainClock>=.02){this.brainClock-=.02;this.brain.step(this.game.capture(),this.mode,this.game.elapsed)}const s=FlyEncoder.encode(this.game.capture());this.gameRenderer.render(this.game,s.lc4);if(now-this.renderClock>=(this.slow?100:40)){this.brainRenderer.render(this.brain.activity??new Uint8Array(this.result?.activityFrame??new ArrayBuffer(8192)));this.renderClock=now}this.updateHud();this.frames++;if(now-this.fpsAt>=1000){this.fps=this.frames*1000/(now-this.fpsAt);this.frames=0;this.fpsAt=now}requestAnimationFrame(t=>this.loop(t))}
  private onBrain(r:BrainResult){this.latency=performance.now()-r.timestamp;this.result=r;this.activity=r.activity;if(r.readoutModel)localStorage.setItem('fly-readout-v2',JSON.stringify(r.readoutModel));if(r.decision==='FLAP')this.game.flap();this.renderData(r)}
  private die(cause:string){if(this.state!=='RUNNING')return;this.state='DEAD';const rec={flyId:this.flyId,mode:this.mode,score:this.game.score,lifetime:this.game.elapsed,totalSpikes:this.result?.totalSpikes??0,at:Date.now()};ExperimentHistory.add(rec);const d=this.$('death');d.classList.remove('hidden');d.innerHTML=`<small>EXPERIMENT TERMINATED</small><h2>FLY #${this.flyId} DIED</h2><div class="death-grid"><span>SCORE<b>${this.game.score} PIPES</b></span><span>LIFETIME<b>${this.game.elapsed.toFixed(1)} SEC</b></span><span>TOTAL SPIKES<b>${(this.result?.totalSpikes??0).toLocaleString()}</b></span></div><h3>CAUSE OF DEATH <i>ENTERTAINMENT ONLY</i></h3><p>${cause}</p><button id="revive">REVIVE FLY →</button>`;(d.querySelector('#revive') as HTMLButtonElement).onclick=()=>this.restart();this.renderLeaders();if(this.autoRevive)this.autoTimer=window.setTimeout(()=>this.restart(),2000)}
  private restart(){clearTimeout(this.autoTimer);this.flyId++;this.seed++;this.game.reset(this.seed);this.brain?.reset(this.seed);this.result=undefined;this.activity=empty;this.$('death').classList.add('hidden');this.$('flyLabel').textContent=`FLY #${this.flyId}`;if(this.state==='READY')this.start();else{this.state='RUNNING';this.game.start();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}}
  private setMode(mode:Mode){this.mode=mode;this.$b('pure').classList.toggle('active',mode==='pure');this.$b('trained').classList.toggle('active',mode==='trained');this.$('modeLabel').textContent=mode==='pure'?'PURE':'TRAINED';this.renderData(this.result)}
  private renderData(r?:BrainResult){const a=r?.activity??this.activity;this.$('sensors').innerHTML=[['LC4',a.lc4],['LPLC2',a.lplc2],['LC10a-L',a.lc10Left],['LC10a-R',a.lc10Right],['UPWARD',a.upward],['DOWNWARD',a.downward]].map(([n,v])=>this.meter(String(n),Number(v))).join('');this.$('motor').innerHTML=this.meter('DNp01',a.dnp01);const flap=r?.decision==='FLAP';this.$('decision').textContent=flap?'↑ FLAP':'· WAIT';this.$('decision').classList.toggle('flap',flap);this.$('prob').textContent=this.mode==='trained'?`FLAP ${Math.round((r?.flapProbability??0)*100)}% · ${r?.trainingSamples??0} SAMPLES · LOSS ${(r?.trainingLoss??0).toFixed(3)}`:'2 SPIKES / 100 MS · COOLDOWN 120 MS';this.$('sequence').textContent=this.slow?(a.lc4>.1?(a.dnp01>.2?'DESCENDING NEURON ACTIVE → MOTOR COMMAND':'VISUAL INPUT DETECTED → SIGNAL PROPAGATING…'):'WAITING FOR SENSORY INPUT'):'LIVE SPIKE FIELD';this.$('step').textContent=`${(r?.stepTime??0).toFixed(1)} MS`}
  private meter(name:string,value:number){return `<div class="meter"><div><b>${name}</b><span>${Math.round(value*100)}%</span></div><i><em style="width:${value*100}%"></em></i></div>`}
  private updateHud(){this.$('score').textContent=String(this.game.score);this.$('best').textContent=String(Math.max(this.game.score,ExperimentHistory.best()));this.$('fps').textContent=`${Math.round(this.fps)} FPS`;if(location.search.includes('debug=1'))this.$('sequence').title=`worker latency ${this.latency.toFixed(2)} ms`}
  private renderLeaders(){const rows=ExperimentHistory.leaders();this.$('leaders').innerHTML=rows.length?rows.map((r,i)=>`<li><span>#${i+1} FLY #${String(r.flyId).padStart(3,'0')}</span><b>${r.score}</b></li>`).join(''):'<li><span>NO COMPLETED FLIGHTS</span><b>—</b></li>'}
  private fastTrain(){if(!this.brain||this.state==='LOADING_CONNECTOME'||this.state==='ERROR')return;this.game.stop();this.setMode('trained');this.$('training').classList.remove('hidden');this.$b('fastTrain').disabled=true;this.brain.fastTrain(1200)}
  private trainingProgress(done:number,total:number,loss:number){const value=done/total;this.$('trainBar').style.width=`${value*100}%`;this.$('trainPct').textContent=`${Math.round(value*100)}%`;this.$('trainText').textContent=`${done.toLocaleString()} / ${total.toLocaleString()} neural samples · loss ${loss.toFixed(3)}`}
  private trainingDone(model:unknown,samples:number,loss:number){localStorage.setItem('fly-readout-v2',JSON.stringify(model));this.$('training').classList.add('hidden');this.$b('fastTrain').disabled=false;if(this.state==='RUNNING')this.game.start();this.toast(`MODEL READY · ${samples.toLocaleString()} SAMPLES · LOSS ${loss.toFixed(3)}`)}
  private exportModel(){const raw=localStorage.getItem('fly-readout-v2');if(!raw){this.toast('NO TRAINED MODEL YET');return}const model={format:'fly-brain-readout-v2',exportedAt:new Date().toISOString(),model:JSON.parse(raw)};const url=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fly-readout-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);this.toast('MODEL EXPORTED')}
  private async importModel(file?:File){if(!file)return;try{const parsed=JSON.parse(await file.text()),model=parsed.format==='fly-brain-readout-v2'?parsed.model:parsed;if(!Array.isArray(model?.features)||!Array.isArray(model?.weights)||model.features.length!==model.weights.length)throw new Error('Invalid model structure');this.brain.importModel(model);this.$<HTMLInputElement>('modelFile').value=''}catch(error){this.toast(`IMPORT FAILED · ${error instanceof Error?error.message:'INVALID FILE'}`)}}
  private toast(message:string){const el=this.$('toast');el.textContent=message;el.classList.remove('hidden');window.setTimeout(()=>el.classList.add('hidden'),2600)}
  private progress(v:number,label:string){this.$('loadBar').style.width=`${v*100}%`;this.$('loadPct').textContent=`${Math.round(v*100)}%`;this.$('loadText').textContent=label}
  private $<T extends HTMLElement=HTMLElement>(id:string){return document.getElementById(id) as T} private $b(id:string){return this.$<HTMLButtonElement>(id)}
}
